/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas.vistas;

import Controlador.interfaz.ICoordinadorAplicacion;

/**
 *
 * @author Aaron Burciaga - 262788
 * @author Brian Sandoval - 262741
 * @author Dayanara Peralta - 262695
 * @author María Valdez - 262775
 */
public class PnlConsultar extends javax.swing.JPanel {

    private ICoordinadorAplicacion coordinador;
    private UsuarioDTO usuario;

    /**
     * Creates new form PnlConsultar
     */
    public PnlConsultar(ICoordinadorAplicacion coordinador, UsuarioDTO usuario) {
        this.coordinador = coordinador;
        this.usuario = usuario;
        initComponents();
        removeAll();
        for(EventoDTO proximo : coordinador.consultarEventosProximos(usuario.getId())){
            PnlEvento pnl = new PnlEvento(proximo);
            this.pnlProximos.add(pnl);
            pnlProximos.revalidate();
            pnlProximos.repaint();
        }
        for(EventoDTO pasado : coordinador.consultarEventosPasados(usuario.getId())){
            PnlEvento pnl = new PnlEvento(pasado);
            this.pnlPasados.add(pnl);
            pnlPasados.revalidate();
            pnlPasados.repaint();
        }
        for(EventoDTO cancelado : coordinador.consultarEventosCancelados(usuario.getId())){
            PnlEvento pnl = new PnlEvento(cancelado);
            this.pnlCancelados.add(pnl);
            pnlCancelados.revalidate();
            pnlCancelados.repaint();
        }
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlProximos = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        pnlPasados = new javax.swing.JPanel();
        jScrollBar2 = new javax.swing.JScrollBar();
        pnlCancelados = new javax.swing.JPanel();
        jScrollBar3 = new javax.swing.JScrollBar();
        lblProximos = new javax.swing.JLabel();
        lblPasados = new javax.swing.JLabel();
        lblCancelados = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlProximosLayout = new javax.swing.GroupLayout(pnlProximos);
        pnlProximos.setLayout(pnlProximosLayout);
        pnlProximosLayout.setHorizontalGroup(
            pnlProximosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProximosLayout.createSequentialGroup()
                .addGap(0, 228, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlProximosLayout.setVerticalGroup(
            pnlProximosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPasadosLayout = new javax.swing.GroupLayout(pnlPasados);
        pnlPasados.setLayout(pnlPasadosLayout);
        pnlPasadosLayout.setHorizontalGroup(
            pnlPasadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPasadosLayout.createSequentialGroup()
                .addGap(0, 243, Short.MAX_VALUE)
                .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlPasadosLayout.setVerticalGroup(
            pnlPasadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlCanceladosLayout = new javax.swing.GroupLayout(pnlCancelados);
        pnlCancelados.setLayout(pnlCanceladosLayout);
        pnlCanceladosLayout.setHorizontalGroup(
            pnlCanceladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCanceladosLayout.createSequentialGroup()
                .addGap(0, 228, Short.MAX_VALUE)
                .addComponent(jScrollBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCanceladosLayout.setVerticalGroup(
            pnlCanceladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        lblProximos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblProximos.setText("Eventos Próximos");

        lblPasados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPasados.setText("Eventos Pasados");

        lblCancelados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCancelados.setText("Eventos Cancelados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlProximos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(pnlPasados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(pnlCancelados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblProximos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPasados)
                .addGap(155, 155, 155)
                .addComponent(lblCancelados)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProximos)
                    .addComponent(lblPasados)
                    .addComponent(lblCancelados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlCancelados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPasados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProximos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollBar jScrollBar3;
    private javax.swing.JLabel lblCancelados;
    private javax.swing.JLabel lblPasados;
    private javax.swing.JLabel lblProximos;
    private javax.swing.JPanel pnlCancelados;
    private javax.swing.JPanel pnlPasados;
    private javax.swing.JPanel pnlProximos;
    // End of variables declaration//GEN-END:variables
}
